### PR TITLE
:sparkles: feat: added functionality to input delay in hh:mm:ss format

### LINKED ISSUE #13: Allow entering delay in HH:MM:SS format
This is a nice tool, thank you for making it. 

One suggestion: it would be a nice QoL improvement if a user could enter the delay in HH:MM:SS format. Right now it seems that the delay is entered in minutes.

### PR DESCRIPTION
**Pull request by PranjalAgni**
Added functionality, of parsing time in hh:mm:ss format

Closes #13

### CODE REVIEW

**Comment by remram44** [comment]
Thanks @PranjalAgni! This doesn't seem to work with strings like `-12:45` or `4:32`, so you probably missed that corner-case :wink:

**Comment by PranjalAgni** [comment]
Made the appropriate changes, have a look

**Comment by PranjalAgni** [comment]
Hi @remram44 just a request can you please add "hacktoberfest-accepted" label to this PR so my efforts are counted for Hacktoberfest

**Comment by remram44** [comment]
Oh I wasn't aware of this change. I suppose that means none of my own PRs are going to count...

I will add the "hacktoberfest" topic to the repository instead.

**Pull request merged**
